FROM nginx:latest

COPY nginx.conf /etc/nginx/conf.d/default.conf

# If you need to copy other files or directories
# COPY other_directory /path/in/container

# If you need to install any packages
# RUN apt-get update && apt-get install -y some-package

EXPOSE 8080
